version: '2'
services:
  es_workshop:
    build:
      context: .
      dockerfile: Dockerfile
    command: python
    links:
     - elasticsearch
    depends_on:
     - elasticsearch
    volumes:
     - .:/project

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    container_name: elasticsearch
    environment:
      - cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - "discovery.type=single-node"
      - "http.cors.enabled=true"
      - "http.cors.allow-origin=*"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200

